### PR TITLE
Read timestamp staleness for read-only transactions

### PR DESCRIPTION
**Pull request by yfuruyama**
Add another staleness option, `read timestamp` for read-only transaction.

With this change, users can use the following two options for staleness read.
```
# exact staleness (10 sec old)
BEGIN RO 10;

# read timestamp (at 2020-03-30T12:00:00.045123456Z)
BEGIN RO 2020-03-30T12:00:00.045123456Z;
```

This PR also has refactoring for tests.

close https://github.com/cloudspannerecosystem/spanner-cli/issues/28

### CODE REVIEW

**Comment by apstndb** [comment]
Not all person know about the spec of `time.RFC3339Nano` so it would be better to document the valid timestamp format.
Especially, some formats are valid in Cloud Spanner timestamps but not in `time.RFC3339Nano`,
https://cloud.google.com/spanner/docs/data-types?hl=en#for-sql-queries

For examples(may be not exhaustive)

## Pass:
```
# canonical format
2020-03-30T12:00:00.123456789Z
# variable fractional digits
2020-03-30T12:00:00Z
2020-03-30T12:00:00.123Z
2020-03-30T12:00:00.123456Z
# time zone by offset
2020-03-30T12:00:00+09:00
```

## Fail:
```
# without seconds
2020-03-30T12:00Z
# separate date and time by space
2020-03-30 12:00:00Z
# without time zone
2020-03-30T12:00:00
# with time zone name
2020-03-30T12:00:00 Asia/Tokyo
# offset without minutes
2020-03-30T12:00:00+09
# without 0-pad
2020-3-30T12:0:0Z
```

**Comment by yfuruyama** [comment]
Re: timestamp format,
Yes, I added description to README: https://github.com/cloudspannerecosystem/spanner-cli/pull/31/commits/1de7d7d71955d4a94295b79cc32bd6034468a573.
We only allows users to use RFC3339 (ISO 8601) format for the read timestamp.

**Comment by apstndb** [comment]
OK, it is strictly RFC3339 with up to 9 DIGIT.
https://tools.ietf.org/html/rfc3339#section-5.6

**Comment by apstndb** [comment]
I wonder it is convenient to support time.Duration text format(e.g. `30m` and `500ms`) for exact staleness.

**Comment by yfuruyama** [comment]
> I wonder it is convenient to support time.Duration text format(e.g. 30m and 500ms) for exact staleness.

Sounds good. I guess the current format (number in second) is fine for most of cases, but I understand time.Duration text format would be more intuitive for big number.

Let's consider it in another place.

**Pull request merged**
