### PR TITLE
Add CLI flag `--skip-tls-verify`

### PR DESCRIPTION
**Pull request by iwinux**
The `--endpoint` flag (added by https://github.com/cloudspannerecosystem/spanner-cli/pull/162) allows spanner-cli to connects to a custom API endpoint.

However, gRPC will only send credentials (specified by `--credentials` or env `GOOGLE_APPLICATION_CREDENTIALS`) when TLS is enabled. To ease some use cases during local testing, this pull request adds `--skip-tls-verify` which implicitly enables TLS while skipping certificate verification.

### CODE REVIEW

**Comment by yfuruyama** [comment]
> To ease some use cases during local testing

Could you elaborate on your use case where you have to skip certificate verification? 

I think #162 was supposed to be used for some endpoints listed the following doc, but every endpoint uses proper TLS ceritification: https://cloud.google.com/spanner/docs/endpoints

**Comment by iwinux** [comment]
The use case involves sending Spanner queries through a local gRPC proxy (for internal logging purpose). The proxy itself is using TLS with self-signed certificate. As of security concern, the usage is not exposed to public Internet, therefore skipping verification is acceptable.

**Comment by yfuruyama** [comment]
@iwinux Thank you for sharing that. That sounds a reasonable use case.

I want to merge this, but looks like CLA is not signed yet.

**Comment by iwinux** [comment]
@yfuruyama I've signed it just now.

**Comment by yfuruyama** [comment]
@iwinux Thanks! Could you update README with a new option? https://github.com/cloudspannerecosystem/spanner-cli/blob/master/README.md?plain=1#L33-L57

**Comment by yfuruyama** [comment]
@iwinux Thank you!

**Review by yfuruyama — APPROVED** [review]

**Pull request merged**
