### PR TITLE
Support JSON data type

### PR DESCRIPTION
**Pull request by yfuruyama**
Today [JSON data type](https://cloud.google.com/spanner/docs/data-types#json_type) was [announced](https://cloud.google.com/spanner/docs/release-notes#August_30_2021) and this PR supports that in spanner-cli.

Example:
```
spanner> show create table t1;
+-------+----------------------------+
| Table | Create Table               |
+-------+----------------------------+
| t1    | CREATE TABLE t1 (          |
|       |   id INT64 NOT NULL,       |
|       |   j1 JSON NOT NULL,        |
|       |   j2 JSON,                 |
|       |   j3 ARRAY<JSON> NOT NULL, |
|       |   j4 ARRAY<JSON>,          |
|       | ) PRIMARY KEY(id)          |
+-------+----------------------------+
1 rows in set (0.88 sec)

insert into t1 (id, j1, j2, j3, j4) values (1, JSON '{"a": "b"}', NULL, [JSON '[1, 2, 3]', JSON '{"foo": null}'], NULL);

spanner> select * from t1;
+----+-----------+------+-------------------------+------+
| id | j1        | j2   | j3                      | j4   |
+----+-----------+------+-------------------------+------+
| 1  | {"a":"b"} | NULL | [[1,2,3], {"foo":null}] | NULL |
+----+-----------+------+-------------------------+------+
1 rows in set (5.97 msecs)

spanner> select parse_json('{"a": 10}');
+----------+
|          |
+----------+
| {"a":10} |
+----------+
1 rows in set (21.26 msecs)
```

### CODE REVIEW

**Comment by yfuruyama** [comment]
@apstndb Could you review this PR when you have a chance? Thanks!

**Review by apstndb — COMMENTED** [review]
Almost LGTM.
I think it is better to add the test case about JSON null values are distinguished from NULL as spec.
```
> SELECT JSON "null", CAST(NULL AS JSON);
+------+------+
|      |      |
+------+------+
| null | NULL |
+------+------+
1 rows in set (1.47 msecs)
```

**Comment by yfuruyama** [comment]
> I think it is better to add the test case about JSON null values are distinguished from NULL as spec.

Good point! I added the test case: https://github.com/cloudspannerecosystem/spanner-cli/pull/118/commits/21b073aaca294e4cb8787ad2bff32be5fd59265e

**Review by apstndb — APPROVED** [review]
LGTM

**Pull request merged**
