### PR TITLE
Show query stats in verbose mode

### PR DESCRIPTION
**Pull request by yfuruyama**
## Stats fields

I chose following fields for display.

- elapsed (Total elapsed time)
- cpu (CPU time)
- scanned (Rows scanned)
- optimizer (Optimizer version)

These fields are equivalent to the output for `gcloud spanner databases execute-sql --query-mode=PROFILE`.

## Example

Query:
```
spanner> select * from t1;
+------+
| T1Id |
+------+
| 1    |
| 2    |
| 3    |
| 4    |
| 5    |
+------+
5 rows in set (2.69 msecs)
timestamp: 2020-04-19T13:11:03.496776+09:00
cpu:       1.11 msecs
scanned:   5 rows
optimizer: 2
```

Mutation:
```
spanner> insert into t1 (T1Id) values (6), (7), (8);
Query OK, 3 rows affected (5.42 sec)
timestamp: 2020-04-19T13:31:08.064703+09:00
```

## Other changes
Following statements used `SelectStatement` to execute query for INFORMATION SCHEMA, but it was not an ideal way since it uses user's transaction implicitly and also query stats doesn't have meaningful information.

- `SHOW TABLES`
- `SHOW COLUMNS`
- `SHOW INDEX`

So I changed to use standalone read-only transaction to execute those queries.

## TODO
- [x] Fix timestamp output for mutation result
- [x] Fix existing test
- [x] Add tests

close https://github.com/cloudspannerecosystem/spanner-cli/issues/37

---

## Example (obsolete: single line)

Query:
```
spanner> select * from t1;
+------+
| T1Id |
+------+
| 1    |
| 2    |
| 3    |
| 4    |
| 5    |
+------+
5 rows in set (elapsed: 2.89 msecs, cpu: 0.98 msecs, scanned: 5 rows, optimizer: 2, timestamp: 2020-04-18T23:43:43.728042+09:00)
```

Mutation:

```
spanner> insert into t1 (T1Id) values (6), (7), (8);
Query OK, 3 rows affected (elapsed: 1.21 sec, timestamp: 2020-04-18T23:45:22.310926+09:00)
```

### CODE REVIEW

**Comment by yfuruyama** [comment]
@apstndb Please take a look at an example. Do you think it's too long for display?

**Comment by apstndb** [comment]
I feel that it is too long because the line is 128 character width and not fit in GitHub page.
Affected row and read/commit timestamp and query stats are another sourced values so
it makes sense to separate line.

Additionally, I am thinking about `QueryStats` struct.
Currently, all fields are string and there are no logics so `Result.Stats` can be typed as  `map[string]interface{}`.
`interface{}`-valued map is not pretty but there are some pros.
Shown key can be dynamically configurable if new stats value are added.

**Comment by yfuruyama** [comment]
It looks too long, but please note that this is the output of `--verbose` mode. Anyway, let me find another format for better, concise output.

Regarding stats fields, I don't want to introduce another command line option for now to configure displayed values, other than `--verbose` option. If other stats fields are needed to investigate queries, I would recommend users to create a custom script or use another dedicated tool like [rakyll/spannerbench](https://github.com/rakyll/spannerbench).

**Comment by apstndb** [comment]
Yeah, I would use `gcloud spanner databases execute-sql --query-mode=PROFILE --format=yaml` for general stats.
IMO, I want timestamp is always display if display area is narrow and there are no line wrap.

**Comment by yfuruyama** [comment]
I didn't know that gcloud with `--format=yaml` shows an entire query stats. That's good to know :)

> IMO, I want timestamp is always display if display area is narrow and there are no line wrap.

Could you elaborate what this means? Appreciated if you can show sample output.

**Comment by apstndb** [comment]
It means I prefer
```
5 rows in set (timestamp: 2020-04-18T23:43:43.728042+09:00, elapsed: 2.89 msecs, cpu: 0.98 msecs, scanned: 5 rows, optimizer: 2)
```
than
```
5 rows in set (elapsed: 2.89 msecs, cpu: 0.98 msecs, scanned: 5 rows, optimizer: 2, timestamp: 2020-04-18T23:43:43.728042+09:00)
```
because I want to talk about timestamps.
If there are only single `--verbose` option and single-lined output,  ordering is important.

**Comment by yfuruyama** [comment]
Thanks, I don't have any preference for ordering, but I wondered if most users really care about timestamp as it is only used for stale read.

For multi line display, I created a sample output like this. What do you think?

Query:
```
spanner> select * from t1;
+------+
| T1Id |
+------+
| 1    |
| 2    |
| 3    |
| 4    |
| 5    |
+------+
5 rows in set (2.89 msecs)

timestamp: 2020-04-18T23:43:43.728042+09:00
cpu:       0.98 msecs
scanned:   5 rows
optimizer: 2

spanner> ...
```

Mutation:
```
spanner> insert into t1 (T1Id) values (6), (7), (8);
Query OK, 3 rows affected (1.21 sec)

timestamp: 2020-04-18T23:45:22.310926+09:00

spanner> ...
```

**Comment by apstndb** [comment]
I prefer multiple line to single line.
Another option is collapsing query stats into single line.
```
5 rows in set(elapsed: 2.89 msecs)
timestamp: 2020-04-18T23:43:43.728042+09:00
cpu: 0.98 msecs, scanned: 5 rows, optimizer: 2
```

**Comment by yfuruyama** [comment]
Thanks for another option! Collapsing stats into a single line looked a little bit dense for me. Especially it could be hard to tell each field at a glance.

Well, then let me rewrite with multi-line format tomorrow 👍

**Comment by apstndb** [comment]
I am wondering why this PR restrict `SHOW TABLES` etc  in R/O tx.
`INFORMATION_SCHEMA` with stale read is [explicitly possible](https://cloud.google.com/spanner/docs/information-schema?hl=en#usage) and sometime useful when the schema has changed recently.

**Comment by yfuruyama** [comment]
I changed it because it's not obvious for users that `SHOW TABLES` etc uses `INFORMATION SCHEMA` internally to build the result. In other words, it's not desirable situation where users depend on the fact that we use `INFORMATION_SCHEMA` to get the result for some statements.

If users want to check table schema for the past time, I guess they can query `INFORMATION_SCHEMA` directly in the read-only transaction.

**Comment by apstndb** [comment]
IMO, it would be better to emit the warning about staleness read rather than error.
Once the warning is displayed, this behavior should not be confusing.

**Comment by yfuruyama** [comment]
hmm.. ok, I understand to some extent there is a merit to allow users to run `SHOW TABLES` in read-only transactions. I think showing warning is a little bit noisy.

Fixed in https://github.com/cloudspannerecosystem/spanner-cli/pull/45/commits/777545b373ee6e7bfecb061e2e4dfe0685ded161.

**Comment by yfuruyama** [comment]
Thank you for the detailed review, as always!

**Pull request merged**
